[package]
name = "rust-site"
version = "0.1.0"
edition = "2024"

[dependencies]
mlua = { version = "0.10.5", features = ["lua54", "vendored"] }
serde = { version = "1.0.219", features = ["derive"] }
toml = { version = "0.8.23" }